# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Manipulator move with tcp
#The vale of coordinate order is {x,y,z,rx,ry,rz}

int32 LEBAI_LM3_CLAW_90 = 0

int32 manipulator_id
float64 speed
float64 acc
float64 time
float64 radius
geometry_msgs/Pose pose

---
bool result
