# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Check target tcp pose if reachable

# Manipulator move with tcp
#The vale of coordinate order is {x,y,z,x,y,z,w}

int32 manipulator_id
geometry_msgs/Pose pose

---
bool result
