# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Claw control

int32 manipulator_id
float64[] force
float64[] amplitude
---
bool result
